import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

function getGitOutput(command: string): string | null {
	try {
		return execSync(command, {
			encoding: 'utf-8',
			stdio: ['ignore', 'pipe', 'ignore'],
		}).trim();
	} catch {
		return null;
	}
}

function generateBuildInfo(): void {
	const rootDir = process.cwd();
	const packageJsonPath = path.join(rootDir, 'package.json');
	const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8')) as {
		name?: string;
		version?: string;
	};

	const version = packageJson.version || '0.0.0';
	const commit =
		process.env.COMMIT_SHA || getGitOutput('git rev-parse HEAD') || 'unknown';
	const commitShort =
		process.env.COMMIT_SHORT_SHA ||
		(commit !== 'unknown'
			? commit.slice(0, 7)
			: getGitOutput('git rev-parse --short HEAD') || 'unknown');
	const branch =
		process.env.GIT_BRANCH ||
		getGitOutput('git rev-parse --abbrev-ref HEAD') ||
		'unknown';
	const dirtyOutput = getGitOutput('git status --porcelain');
	const dirty = dirtyOutput !== null ? dirtyOutput.length > 0 : false;
	const builtAt = new Date().toISOString();

	const targetPath = path.join(rootDir, 'src', 'lib', 'buildInfo.generated.ts');

	const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Generated by scripts/generateBuildInfo.ts on ${builtAt}
 */

export interface BuildInfo {
	version: string;
	commit: string;
	commitShort: string;
	branch: string;
	dirty: boolean;
	builtAt: string;
}

export const BUILD_INFO: BuildInfo = {
	version: ${JSON.stringify(version)},
	commit: ${JSON.stringify(commit)},
	commitShort: ${JSON.stringify(commitShort)},
	branch: ${JSON.stringify(branch)},
	dirty: ${JSON.stringify(dirty)},
	builtAt: ${JSON.stringify(builtAt)},
} as const;
`;

	fs.writeFileSync(targetPath, fileContent, 'utf-8');
	console.log(
		`✅ Generated build metadata: v${version} (${commitShort} on ${branch}) at ${targetPath}`,
	);
}

generateBuildInfo();
